openapi: 3.0.0
info:
  version: 1.0.0
  title: Heureka Marketplace API
  description: Public documentation of Heureka Marketplace API services.
servers:
  - url: https://ssl.heureka.sk/
    description: For SK partners
  - url: https://ssl.heureka.cz/
    description: For CZ partners

paths:
  # CZ/SK EGRESS
  /api/1/products/availability:
    $ref: '../egress/products/paths/products-availability.yml'
    servers:
      - url: https://example-partner-api.com/
        description: for egress calls
  /api/1/payment/delivery:
    $ref: '../egress/payment/paths/payment-delivery.yml'
    servers:
      - url: https://example-partner-api.com/
        description: for egress calls

  # CZ/SK/HU/RO INGRESS
  /api/cart/{apiKey}/1/payout-report:
    $ref: '../ingress/payment/paths/payout-report.yml'
