openapi: 3.0.0

info:
paths:

components:
  parameters:
  schemas:

  responses:
    SuccessResponse:
      description: Payout Report CSV generated successfully.
      content:
        text/csv:
          schema:
            description: Payout data in CSV format
            type: string
            example: "column1;column2;column3;...\ndata1;data2;data3;..."
    ValidationErrorResponse:
      description: Show validation error response
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: Validation error(s)!
              code:
                type: integer
                example: 422
              version:
                type: string
                description: The version of the API
                example: v1.0.0
              uuid:
                type: string
                format: uuid
                example: a1b47cd1-1234-4ab2-a12b-1234bd0a4bc3
              data:
                type: array
                nullable: true
                example: []
                items:
                  type: object
              errors:
                type: object
                properties:
                  day:
                    type: array
                    items:
                      type: string
                      example: validation.required
